---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: posts
  label: posts
  create: all
  match: "**/*.md"
upload_dir: sample-lume-blog
public_path: sample-lume-blog
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: _site
  preview_docker_image: denoland/deno:1.13.0
  mount_path: "/app"
  working_dir: "/app"
  instant_preview_command: deno run -A https://deno.land/x/lume/ci.ts
